// LOTSGAME ゲームデータ (33レコード x 3フィールド = 99項目)
// cat: party=パーティー mystery=人狼・推理 quiz=クイズ・ことば board=ボード・カード
//      io=.io対戦 shooter=シューター・スポーツ solo=1人でも神ゲー
const GAMES = [
  // ── お絵かき・パーティー ──────────────────────────────
  { id: "gartic-phone", name: "Gartic Phone", url: "https://garticphone.com/ja", desc: "絵の伝言ゲーム。ズレていく絵に爆笑", players: "4〜15人", cat: "party", emoji: "🎨" },
  { id: "skribbl", name: "skribbl.io", url: "https://skribbl.io", desc: "定番お絵かきクイズ。合言葉で友達部屋", players: "2〜12人", cat: "party", emoji: "✏️" },
  { id: "gartic-io", name: "Gartic.io", url: "https://gartic.io", desc: "お絵かき当てゲームの老舗", players: "〜10人", cat: "party", emoji: "🖌️" },
  { id: "drawasaurus", name: "Drawasaurus", url: "https://www.drawasaurus.org", desc: "サクサク遊べるお絵かきクイズ", players: "2〜10人", cat: "party", emoji: "🦖" },
  { id: "sketchful", name: "Sketchful.io", url: "https://sketchful.io", desc: "きれいな画面のお絵かきクイズ", players: "2〜10人", cat: "party", emoji: "🖍️" },
  { id: "makeitmeme", name: "Make It Meme", url: "https://makeitmeme.com/ja", desc: "ミームで大喜利バトル", players: "3〜8人", cat: "party", emoji: "😂" },
  { id: "deathbyai", name: "Death by AI", url: "https://deathbyai.gg", desc: "AIが生死を判定するサバイバル大喜利", players: "1〜10人", cat: "party", emoji: "💀" },
  { id: "jklm", name: "JKLM.fun", url: "https://jklm.fun", desc: "爆弾が爆発する前に単語を言え!", players: "2〜16人", cat: "party", emoji: "💣" },
  { id: "stopots", name: "StopotS", url: "https://stopots.com", desc: "お題×頭文字のスピード連想ゲーム", players: "2〜14人", cat: "party", emoji: "🛑" },
  { id: "justfall", name: "JustFall.LOL", url: "https://justfall.lol", desc: "ペンギンで床が消えるパーティー", players: "〜10人", cat: "party", emoji: "🐧" },
  { id: "gooberdash", name: "Goober Dash", url: "https://gooberdash.winterpixel.com", desc: "障害物レースのパーティーロイヤル", players: "〜8人", cat: "party", emoji: "🏃" },
  { id: "rocketbot", name: "Rocket Bot Royale", url: "https://rocketbotroyale.winterpixel.com", desc: "戦車で撃ち合うバトルロイヤル", players: "〜10人", cat: "party", emoji: "🚀" },
  { id: "stumbleguys", name: "Stumble Guys (Web版)", url: "https://poki.com/ja/g/stumble-guys", desc: "大人数おバカ障害物レース", players: "〜32人", cat: "party", emoji: "🤪" },
  { id: "bonk", name: "Bonk.io", url: "https://bonk.io", desc: "物理で押し出す対戦。友達部屋OK", players: "〜8人", cat: "party", emoji: "⚽" },
  { id: "haxball", name: "HaxBall", url: "https://www.haxball.com", desc: "みんなでゆるサッカー。部屋作成可", players: "2〜12人", cat: "party", emoji: "🥅" },
  { id: "lounge", name: "ラウンジ(終われまてん)", url: "https://loungegame.site", desc: "「一致するまで終われまテン」など配信者定番パーティー集", players: "2人〜", cat: "party", emoji: "🛋️" },
  { id: "ngword", name: "NGワード(ラウンジ)", url: "https://loungegame.site", desc: "頭の上のNGワードを相手に言わせたら勝ち!", players: "2人〜", cat: "party", emoji: "🙊" },
  { id: "kahoot", name: "Kahoot!", url: "https://kahoot.it", desc: "世界定番のクイズ大会。PINだけで参加", players: "何人でも", cat: "party", emoji: "❓", img: "img/thumbs/kahoot.svg" },
  { id: "jackbox", name: "Jackbox Games", url: "https://jackbox.tv", desc: "実況者御用達パーティー集(参加はブラウザ無料)", players: "〜10人", cat: "party", emoji: "📦", img: "img/thumbs/jackbox.svg" },
  { id: "drawaria", name: "Drawaria.online", url: "https://drawaria.online", desc: "お絵かき当て+自由らくがき部屋", players: "〜30人", cat: "party", emoji: "🖼️", img: "img/thumbs/drawaria.svg" },
  { id: "bpp", name: "Broken Picture Phone", url: "https://www.brokenpicturephone.com", desc: "絵の伝言ゲーム。ガーティック系の自由版", players: "3人〜", cat: "party", emoji: "📞", img: "img/thumbs/bpp.svg" },
  { id: "betrayal", name: "Betrayal.io", url: "https://betrayal.io", desc: "Among Us風の裏切り者探しをブラウザで", players: "〜12人", cat: "mystery", emoji: "🔪", img: "img/thumbs/betrayal.svg" },
  { id: "gamebuddies", name: "GameBuddies.io", url: "https://gamebuddies.io", desc: "クイズ・お絵かき等16種。配信チャット連携も", players: "2人〜", cat: "party", emoji: "🎪" },
  { id: "gamingcouch", name: "Gaming Couch", url: "https://gamingcouch.com", desc: "スマホがコントローラーになるパーティー集", players: "1〜8人", cat: "party", emoji: "📱" },
  { id: "latelate", name: "らてらて", url: "https://late-late.jp", desc: "ウミガメのスープ(水平思考)をみんなで出題・推理", players: "2人〜", cat: "mystery", emoji: "🐢" },
  { id: "ccfolia", name: "ココフォリア", url: "https://ccfolia.com", desc: "TRPG・マダミスのオンライン卓の定番", players: "2〜8人", cat: "mystery", emoji: "🎭" },

  // ── 謎解き・協力 ──────────────────────────────────────
  { id: "beespiel", name: "ビーシュピール", url: "https://beespiel.net", desc: "無料の協力謎解き専門サイト。通話しながら◎", players: "2〜4人", cat: "escape", emoji: "🧩" },
  { id: "gakuyume", name: "学園祭の夢を見る。", url: "https://gakuyume.web.app", desc: "無料長編!学園祭が舞台の本格協力謎解き", players: "1〜6人", cat: "escape", emoji: "🏫" },
  { id: "dasshutsu", name: "脱出ゲームメーカー", url: "https://dasshutsu.games", desc: "みんなが作った脱出ゲームが遊び放題", players: "1人〜", cat: "escape", emoji: "🚪" },
  { id: "enchambered", name: "Enchambered", url: "https://enchambered.com/puzzles/", desc: "2人が別画面を見て協力する脱出(英語)", players: "2人", cat: "escape", emoji: "🔒" },
  { id: "nazohiroba", name: "ナゾヒロバ", url: "https://nazohiroba.com", desc: "オンライン謎解きの巨大ポータル。無料も多数", players: "1人〜", cat: "escape", emoji: "🔍" },

  // ── 人狼・推理 ──────────────────────────────────────
  { id: "ruru", name: "るる鯖 人狼", url: "https://ruru-jinro.net", desc: "日本語で遊べる本格オンライン人狼", players: "5人〜", cat: "mystery", emoji: "🐺" },
  { id: "onuw", name: "ワンナイト人狼", url: "https://netgames.io/games/onu-werewolf/", desc: "スマホだけで一夜の人狼(netgames)", players: "3〜10人", cat: "mystery", emoji: "🌙" },
  { id: "spyfall", name: "Spyfall", url: "https://netgames.io/games/spyfall/", desc: "場所を知らないスパイは誰だ?", players: "3〜10人", cat: "mystery", emoji: "🕵️" },
  { id: "avalon", name: "Avalon", url: "https://netgames.io/games/avalon/", desc: "正体隠匿の名作をブラウザで", players: "5〜10人", cat: "mystery", emoji: "⚔️" },
  { id: "secretdictator", name: "Secret Dictator", url: "https://netgames.io/games/secret-dictator/", desc: "陣営を見抜く正体隠匿ゲーム", players: "5〜10人", cat: "mystery", emoji: "🎩" },
  { id: "loveletter", name: "Love Letter", url: "https://netgames.io/games/love-letter/", desc: "手札1枚の心理戦カードゲーム", players: "2〜4人", cat: "mystery", emoji: "💌" },
  { id: "codenames", name: "Codenames", url: "https://codenames.game", desc: "チーム対抗ワード連想の金字塔", players: "4人〜", cat: "mystery", emoji: "🔑" },
  { id: "longwave", name: "Wavelength (Longwave)", url: "https://longwave.web.app", desc: "感覚をすり合わせるチーム戦", players: "4人〜", cat: "mystery", emoji: "📻" },
  { id: "wolvesville", name: "Wolvesville", url: "https://www.wolvesville.com", desc: "世界中と遊べる人狼(Web/アプリ)", players: "5人〜", cat: "mystery", emoji: "🌕" },

  // ── クイズ・ことば・タイピング ──────────────────────
  { id: "protobowl", name: "Protobowl", url: "https://protobowl.com", desc: "早押しクイズに部屋単位で参戦", players: "1人〜", cat: "quiz", emoji: "🔔" },
  { id: "jeopardylabs", name: "JeopardyLabs", url: "https://jeopardylabs.com", desc: "自作クイズ大会が開ける(司会向き)", players: "何人でも", cat: "quiz", emoji: "🎤" },
  { id: "openguessr", name: "OpenGuessr", url: "https://openguessr.com", desc: "無料のGeoGuessr風・世界どこでしょう", players: "1人〜", cat: "quiz", emoji: "🌍" },
  { id: "cityguesser", name: "City Guesser", url: "https://virtualvacation.us/guess", desc: "実写映像からどの都市か当てろ", players: "1人〜", cat: "quiz", emoji: "🏙️" },
  { id: "geoguessr", name: "GeoGuessr", url: "https://www.geoguessr.com", desc: "ストリートビュー位置当ての本家", players: "1人〜", cat: "quiz", emoji: "📍" },
  { id: "typeracer", name: "TypeRacer", url: "https://play.typeracer.com", desc: "タイピングレース。友達対戦OK", players: "1〜9人", cat: "quiz", emoji: "⌨️" },
  { id: "nitrotype", name: "Nitro Type", url: "https://www.nitrotype.com", desc: "車で競うタイピング対戦", players: "1〜5人", cat: "quiz", emoji: "🏎️" },
  { id: "sushida", name: "寿司打", url: "https://sushida.net", desc: "回転寿司タイピングの定番(スコア勝負)", players: "1人", cat: "quiz", emoji: "🍣" },
  { id: "ztype", name: "ZType", url: "https://zty.pe", desc: "打って撃ち落とすタイピングSTG", players: "1人", cat: "quiz", emoji: "🛸" },

  // ── ボード・カード ──────────────────────────────────
  { id: "bga", name: "Board Game Arena", url: "https://ja.boardgamearena.com", desc: "800種以上のボドゲをオンラインで", players: "2〜10人", cat: "board", emoji: "🎲" },
  { id: "colonist", name: "Colonist", url: "https://colonist.io", desc: "カタン風の開拓ボードゲーム", players: "2〜8人", cat: "board", emoji: "🏝️" },
  { id: "richup", name: "Richup.io", url: "https://richup.io", desc: "モノポリー風を友達部屋で", players: "2〜8人", cat: "board", emoji: "💰" },
  { id: "pokernow", name: "PokerNow", url: "https://www.pokernow.club", desc: "ワンクリックでポーカールーム", players: "2〜10人", cat: "board", emoji: "🃏" },
  { id: "playingcards", name: "PlayingCards.io", url: "https://playingcards.io", desc: "何でもできる自由なカードテーブル", players: "何人でも", cat: "board", emoji: "🂡" },
  { id: "cardgamesio", name: "CardGames.io", url: "https://cardgames.io", desc: "大富豪・ハーツなど定番カード集", players: "1〜4人", cat: "board", emoji: "♠️" },
  { id: "playok", name: "PlayOK", url: "https://www.playok.com/ja/", desc: "リバーシ等、世界の定番ゲーム対戦", players: "2〜4人", cat: "board", emoji: "⚫" },
  { id: "lichess", name: "Lichess", url: "https://lichess.org", desc: "完全無料・広告なしのチェス", players: "2人", cat: "board", emoji: "♞" },
  { id: "chesscom", name: "Chess.com", url: "https://www.chess.com/ja", desc: "世界最大のチェス。変則ルールや友達対戦も", players: "2人", cat: "board", emoji: "♟️" },
  { id: "lishogi", name: "Lishogi", url: "https://lishogi.org", desc: "完全無料の将棋(Lichessの将棋版)", players: "2人", cat: "board", emoji: "🗾" },
  { id: "ogs", name: "Online-Go (OGS)", url: "https://online-go.com", desc: "世界と打てる囲碁", players: "2人", cat: "board", emoji: "⚪" },
  { id: "hanab", name: "Hanab.live", url: "https://hanab.live", desc: "協力型カードゲーム「花火」", players: "2〜6人", cat: "board", emoji: "🎆" },
  { id: "setwf", name: "Set with Friends", url: "https://setwithfriends.com", desc: "リアルタイムSET早取り対戦", players: "1人〜", cat: "board", emoji: "🔺" },
  { id: "dominion", name: "Dominion Online", url: "https://dominion.games", desc: "デッキ構築の名作・公式オンライン", players: "2〜6人", cat: "board", emoji: "👑" },
  { id: "papergames", name: "Papergames.io", url: "https://papergames.io", desc: "四目並べ・○×などミニゲーム対戦", players: "2人", cat: "board", emoji: "📋" },

  // ── .io対戦・サバイバル ──────────────────────────────
  { id: "slither", name: "Slither.io", url: "https://slither.io", desc: "ヘビ大戦争の超定番", players: "大人数", cat: "io", emoji: "🐍" },
  { id: "agar", name: "Agar.io", url: "https://agar.io", desc: "食べて大きくなる細胞バトル", players: "大人数", cat: "io", emoji: "🦠" },
  { id: "diep", name: "Diep.io", url: "https://diep.io", desc: "戦車を育てるシューティング", players: "大人数", cat: "io", emoji: "🛞" },
  { id: "arras", name: "Arras.io", url: "https://arras.io", desc: "Diep進化版のファンメイド", players: "大人数", cat: "io", emoji: "🔷" },
  { id: "moomoo", name: "MooMoo.io", url: "https://moomoo.io", desc: "資源を集めて村を守れ", players: "大人数", cat: "io", emoji: "🏰" },
  { id: "zombs", name: "Zombs.io", url: "https://zombs.io", desc: "ゾンビの夜を基地で生き残れ", players: "大人数", cat: "io", emoji: "🧟" },
  { id: "zombsroyale", name: "ZombsRoyale.io", url: "https://zombsroyale.io", desc: "2Dバトルロイヤル(スマホ◎)", players: "100人", cat: "io", emoji: "🪂" },
  { id: "starve", name: "Starve.io", url: "https://starve.io", desc: "極寒の世界でサバイバル", players: "大人数", cat: "io", emoji: "🥶" },
  { id: "taming", name: "Taming.io", url: "https://taming.io", desc: "ペットと一緒にサバイバル", players: "大人数", cat: "io", emoji: "🐾" },
  { id: "florr", name: "Florr.io", url: "https://florr.io", desc: "花びらを装備して戦うMMO", players: "大人数", cat: "io", emoji: "🌸" },
  { id: "deeeep", name: "Deeeep.io", url: "https://deeeep.io", desc: "海の生き物で食物連鎖を駆け上がれ", players: "大人数", cat: "io", emoji: "🦈" },
  { id: "mope", name: "Mope.io", url: "https://mope.io", desc: "動物進化サバイバル", players: "大人数", cat: "io", emoji: "🦁" },
  { id: "lbs", name: "Little Big Snake", url: "https://littlebigsnake.com", desc: "進化系スネークバトル", players: "大人数", cat: "io", emoji: "🪱" },
  { id: "wormate", name: "Wormate.io", url: "https://wormate.io", desc: "お菓子を食べまくるヘビ", players: "大人数", cat: "io", emoji: "🍩" },
  { id: "paperio2", name: "Paper.io 2", url: "https://poki.com/ja/g/paper-io-2", desc: "ぬりつぶし陣取りの定番", players: "大人数", cat: "io", emoji: "🟧" },
  { id: "superhex", name: "Superhex.io", url: "https://superhex.io", desc: "六角形マスの陣取り合戦", players: "大人数", cat: "io", emoji: "⬡" },
  { id: "splix", name: "Splix.io", url: "https://splix.io", desc: "線で囲んで陣地を広げろ", players: "大人数", cat: "io", emoji: "🟩" },
  { id: "powerline", name: "Powerline.io", url: "https://powerline.io", desc: "電光ヘビのスピードバトル", players: "大人数", cat: "io", emoji: "⚡" },
  { id: "curvefever", name: "Curve Fever Pro", url: "https://curvefever.pro", desc: "線を切らすな!カーブ対戦", players: "2〜6人", cat: "io", emoji: "➰" },
  { id: "territorial", name: "Territorial.io", url: "https://territorial.io", desc: "世界地図で領土を広げる陣取り", players: "大人数", cat: "io", emoji: "🗺️" },
  { id: "openfront", name: "OpenFront", url: "https://openfront.io", desc: "Territorial進化系の領土戦争RTS", players: "大人数", cat: "io", emoji: "🚩" },
  { id: "generals", name: "Generals.io", url: "https://generals.io", desc: "1秒ごとに進む陣取り頭脳戦", players: "2〜8人", cat: "io", emoji: "♟️" },
  { id: "digdig", name: "Digdig.io", url: "https://digdig.io", desc: "掘って食って大きくなる地中バトル", players: "大人数", cat: "io", emoji: "⛏️" },
  { id: "yohoho", name: "Yohoho.io", url: "https://yohoho.io", desc: "海賊のバトルロイヤル", players: "大人数", cat: "io", emoji: "🏴‍☠️" },
  { id: "gats", name: "Gats.io", url: "https://gats.io", desc: "見下ろし型ガンバトル", players: "大人数", cat: "io", emoji: "🔩" },
  { id: "defly", name: "Defly.io", url: "https://defly.io", desc: "ヘリで陣取り&撃ち合い", players: "大人数", cat: "io", emoji: "🚁" },
  { id: "starblast", name: "Starblast.io", url: "https://starblast.io", desc: "宇宙船で鉱石を集めて艦隊戦", players: "大人数", cat: "io", emoji: "🌌" },
  { id: "evades", name: "Evades.io", url: "https://evades.io", desc: "みんなで進む協力回避アクション", players: "大人数", cat: "io", emoji: "💨" },
  { id: "drednot", name: "Drednot.io", url: "https://drednot.io", desc: "みんなで1隻の戦艦を操縦する神ゲー", players: "1〜30人", cat: "io", emoji: "🚢" },
  { id: "survev", name: "Survev.io", url: "https://survev.io", desc: "surviv.io復刻の2Dバトロワ", players: "大人数", cat: "io", emoji: "🎯" },
  { id: "tagpro", name: "TagPro", url: "https://tagpro.koalabeast.com", desc: "ボールで旗取りチーム戦", players: "4〜8人", cat: "io", emoji: "🚩" },
  { id: "bloxd", name: "Bloxd.io", url: "https://bloxd.io", desc: "マイクラ風ミニゲーム集(超人気)", players: "大人数", cat: "io", emoji: "🧱" },
  { id: "mcclassic", name: "Minecraft Classic", url: "https://classic.minecraft.net", desc: "元祖マイクラ。リンク共有で最大9人", players: "1〜9人", cat: "io", emoji: "⛏️" },

  // ── シューター・スポーツ ────────────────────────────
  { id: "krunker", name: "Krunker.io", url: "https://krunker.io", desc: "ブラウザFPSの王様", players: "大人数", cat: "shooter", emoji: "🔫" },
  { id: "shellshock", name: "Shell Shockers", url: "https://shellshock.io", desc: "卵が撃ち合うFPS", players: "大人数", cat: "shooter", emoji: "🥚" },
  { id: "venge", name: "Venge.io", url: "https://venge.io", desc: "サクッと遊べる対戦FPS", players: "〜10人", cat: "shooter", emoji: "🎮" },
  { id: "voxiom", name: "Voxiom.io", url: "https://voxiom.io", desc: "マイクラ風の建築FPS", players: "大人数", cat: "shooter", emoji: "🟫" },
  { id: "kirka", name: "Kirka.io", url: "https://kirka.io", desc: "軽量サクサクのボクセルFPS", players: "大人数", cat: "shooter", emoji: "🗡️" },
  { id: "warbrokers", name: "War Brokers", url: "https://warbrokers.io", desc: "戦車もヘリも乗れるFPS", players: "大人数", cat: "shooter", emoji: "🪖" },
  { id: "narrowone", name: "Narrow.One", url: "https://narrow.one", desc: "弓矢の旗取りチーム戦(スマホ◎)", players: "大人数", cat: "shooter", emoji: "🏹" },
  { id: "repuls", name: "Repuls.io", url: "https://repuls.io", desc: "メカに乗れる近未来FPS", players: "大人数", cat: "shooter", emoji: "🤖" },
  { id: "1v1lol", name: "1v1.LOL", url: "https://1v1.lol", desc: "建築バトル(フォトナ風)", players: "1〜4人", cat: "shooter", emoji: "🏗️" },
  { id: "smashkarts", name: "Smash Karts", url: "https://smashkarts.io", desc: "マリカ風アイテムバトル(超おすすめ)", players: "〜8人", cat: "shooter", emoji: "🏁" },
  { id: "basketbros", name: "BasketBros", url: "https://basketbros.io", desc: "熱血2Dバスケ対戦", players: "2人", cat: "shooter", emoji: "🏀" },
  { id: "tetrio", name: "TETR.IO", url: "https://tetr.io", desc: "ガチ対戦テトリス(99人戦あり)", players: "1〜99人", cat: "shooter", emoji: "🟦" },
  { id: "jstris", name: "Jstris", url: "https://jstris.jezevec10.com", desc: "シンプル爆速の対戦テトリス", players: "1人〜", cat: "shooter", emoji: "🧩" },
  { id: "geofs", name: "GeoFS", url: "https://www.geo-fs.com", desc: "無料フライトシム。世界と同じ空を飛ぶ", players: "大人数", cat: "shooter", emoji: "✈️" },
  { id: "deadshot", name: "Deadshot.io", url: "https://deadshot.io", desc: "いま海外で大人気の軽快対戦FPS", players: "大人数", cat: "shooter", emoji: "🎯" },

  // ── 1人でも神ゲー ────────────────────────────────────
  { id: "quickdraw", name: "Quick, Draw!", url: "https://quickdraw.withgoogle.com", desc: "AIがお絵かきを20秒で当てる", players: "1人", cat: "solo", emoji: "⏱️" },
  { id: "cookie", name: "Cookie Clicker", url: "https://orteil.dashnet.org/cookieclicker/", desc: "伝説の放置クッキーゲー", players: "1人", cat: "solo", emoji: "🍪" },
  { id: "2048", name: "2048", url: "https://play2048.co", desc: "定番スライドパズル", players: "1人", cat: "solo", emoji: "🔢" },
  { id: "slowroads", name: "Slow Roads", url: "https://slowroads.io", desc: "無限に続く道をチルドライブ", players: "1人", cat: "solo", emoji: "🚗" },
  { id: "neal", name: "Neal.fun", url: "https://neal.fun", desc: "不思議おもしろ実験サイト集", players: "1人", cat: "solo", emoji: "🌀" },

  // ── 作ったゲーム(LOTSGAME自作・100本目〜) ──────────────
  { id: "neonbeats", name: "NEON BEATS", url: "rhythm/", desc: "プロセカ風の自作音ゲー!自分の曲でも遊べる", players: "1人", cat: "made", emoji: "🎵", img: "rhythm/thumb.svg" },
  { id: "neonpk", name: "NEON PK", url: "pk/", desc: "3DのPK対決!部屋を作ればキッカーvsキーパーで同時対戦", players: "1〜5人", cat: "made", emoji: "⚽", img: "pk/thumb.svg", badge: "NEW" },
];

const CATS = {
  party:   { label: "パーティー",    color: "#ff6b9d" },
  mystery: { label: "人狼・推理",    color: "#9b6bff" },
  quiz:    { label: "クイズ・ことば", color: "#ffb020" },
  board:   { label: "ボード・カード", color: "#2ecc71" },
  io:      { label: ".io対戦",       color: "#4fc3f7" },
  shooter: { label: "シューター",    color: "#ff5c5c" },
  escape:  { label: "謎解き・協力",   color: "#a3e635" },
  solo:    { label: "1人でも神ゲー", color: "#26c6da" },
  best:    { label: "みんなで遊ぶ神ゲー", color: "#ffcf4d" },
  made:    { label: "作ったゲーム",   color: "#e879ff" },
};

// ── みんなで遊ぶ神ゲー ランキング(実際に盛り上がると実証済みの順・実況者の定番が上位) ──
const BEST = [
  "gartic-phone", "lounge", "ngword", "skribbl", "jklm", "makeitmeme", "onuw", "ruru", "latelate", "smashkarts",
  "deathbyai", "codenames", "beespiel", "spyfall", "betrayal", "justfall", "gooberdash", "stumbleguys", "bonk", "haxball",
  "drawaria", "gartic-io", "gamebuddies", "drawasaurus", "sketchful", "bpp", "gakuyume", "stopots", "jackbox", "kahoot",
  "geoguessr", "openguessr", "cityguesser", "ccfolia", "bga", "colonist", "richup", "pokernow", "avalon", "secretdictator",
  "loveletter", "longwave", "wolvesville", "dasshutsu", "enchambered", "nazohiroba", "gamingcouch", "zombsroyale", "survev", "shellshock",
  "krunker", "deadshot", "1v1lol", "voxiom", "kirka", "venge", "warbrokers", "narrowone", "repuls", "bloxd",
  "mcclassic", "drednot", "tetrio", "jstris", "typeracer", "nitrotype", "protobowl", "jeopardylabs", "rocketbot", "basketbros",
  "tagpro", "curvefever", "slither", "agar", "paperio2", "splix", "superhex", "powerline", "territorial", "openfront",
  "generals", "diep", "arras", "digdig", "yohoho", "gats", "defly", "starblast", "evades", "moomoo",
  "zombs", "starve", "taming", "florr", "deeeep", "mope", "lbs", "wormate", "playingcards", "cardgamesio",
  "playok", "chesscom", "setwf", "hanab", "dominion", "papergames", "lichess", "lishogi", "ogs", "geofs",
];
BEST.forEach((id, i) => { const g = GAMES.find((x) => x.id === id); if (g) g.best = i + 1; });
